### ISSUE TITLE
Polling interval issue

### ISSUE THREAD

**Issue by Wildpipe** [newrelic/nri-perfmon#7]
Hi,

I've got an issue with the polling interval configuration in the file nri-perfmon-definition.yml
I am not able to make the integration respect the interval setting. It doesn't matter if I set the interval value to 10, 60 or 60000 the integration will still continue to poll and report data to NewRelic every 10 seconds. Running nri-perfmon.exe -i 60000 from the command line works though. Appreciate any help I can get in figuring this out.

**Comment by sschwartzman** [comment]
hi @Wildpipe can I see your nri-perfmon-definition.yml file?

**Comment by sschwartzman** [comment]
Ahh, I know why. That interval is for how often the executible gets executed. Because this is a stateful On-Host Integration, it never returns so that interval is not meaningful. I should document this.

If you want to set the interval, you add -i <interval> to that definition file, like so:

```yaml
#
# New Relic Infrastructure Perfmon Integration
#
name: com.newrelic.perfmon
description: Perfmon On-Host Integration
protocol_version: 1
os: windows
commands:
  metrics:
    command:
      - .\nri-perfmon\nri-perfmon.exe
      - -i <interval_here> 
    prefix: integration/nri-perfmon
    interval: 15
```
